"""empty message

Revision ID: 8e50371d8c18
Revises: 
Create Date: 2019-05-10 15:18:44.400998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e50371d8c18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privacy_concerns_data', sa.Column('browserPlugin', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privacy_concerns_data', 'browserPlugin')
    # ### end Alembic commands ###
