"""empty message

Revision ID: b4b2bb567213
Revises: 
Create Date: 2019-05-10 14:41:29.863962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b2bb567213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privacy_concerns_data', sa.Column('browserPlugin', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privacy_concerns_data', 'browserPlugin')
    # ### end Alembic commands ###
